version: 2.1
orbs: 
  aws-s3: circleci/aws-s3@3.0.0
executors: 
  python-executor: 
    docker:
      - image: 'cimg/python:3.6'
    working_directory: /tmp
  node-executor: 
    docker:
      - image: cimg/node:17.2.0
    working_directory: /tmp
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Build
          command: yarn build
      - run: ls
      - persist_to_workspace:
          root: .
          paths:
            - out
  deploy:
    executor: python-executor
    steps:
      - attach_workspace:
          at: /tmp
      - run: ls
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          arguments: '--delete'
          from: out
          to: 's3://cv-ced'
workflows:
  ci:
    jobs:
      - build
      - deploy:
          requires:
            - build