version: 2.1
orbs: 
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - run:
          name: Build
          command: yarn build
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/copy:
          arguments: '--dryrun'
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: bucket/build_asset.txt
          to: 's3://${AWS_S3_NAME}/'
workflows:
  ci:
    jobs:
      - build
      - deploy