version: 2.1
orbs: 
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - run:
          name: Build
          command: yarn build
  deploy:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - run: mkdir out && echo "lorem ipsum" > out/foo.txt
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: out
          to: 's3://cv-ced'
workflows:
  ci:
    jobs:
      - build
      - deploy