version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - run:
          name: Build
          command: yarn build
workflows:
  ci:
    jobs:
      - build
