version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --immutable
      - run:
          name: Build
          command: yarn build
  deploy:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: 
          name: Remove AWS S3 content
          command: aws s3 rm s3://cv-ced/ --recursive
      - run:
          name: Copy files to AWS S3
          command: echo files copied
workflows:
  ci:
    jobs:
      - build
      - deploy